version: '3.8'
services:
  mysql-container:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dbtest
      - MYSQL_USER=user_test
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
